### ISSUE TITLE
Navigation isnt responsive on ultra wide screen (21:9 or higher)

### ISSUE THREAD

**Issue by pr4x77** [Cykotech/link_management_system#1]
Hi,

on ultra wide screen monitors with aspect ratios equal or higher of 21:9 the navigation isnt responsive.

The navbar is always visible and in front of other elements on the site.

When nav should be hidden:
![image](https://github.com/Cykotech/link_management_system/assets/126170201/0e822334-c595-43dc-8827-bafceeddd1e0)

When nav is open:
![image](https://github.com/Cykotech/link_management_system/assets/126170201/d000f2b7-b5f4-4084-a236-03e677a09f61)

Should be fixable with a max-width in your Sidebar.module.scss.

**Comment by Cykotech** [comment]
Thank you for pointing this out to me. It should be fixed now.
